### ISSUE TITLE
Only works with square mazes

### ISSUE THREAD

**Issue by sbj42** [MatthewMcLeod/maze-generator#1]
In its current state, this library can only generate square mazes (where `MAZE_SIZE_ROWS == MAZE_SIZE_COLS`).  There are two bugs that prevent non-square mazes from working.

First, on line 34-35:

```
var seed = [Math.floor(MAZE_SIZE_COLS * Math.random()), Math.floor(MAZE_SIZE_ROWS * Math.random())]
generatePath(maze, seed[0], seed[1])
```

Rows and columns are swapped there.  `generatePath` takes "row, col", but lines 34-35 are set up to call it with "col, row".

Second, on lines 100 and 105:

```
} else if (col == (maze.length - 1)) {
    // ...
} else if (row == (maze[0].length - 1)) {
```

Again rows and columns are swapped. From lines 21-23,  `maze.length` is the number of rows and `maze[0].length` is the number of columns.

**Comment by MatthewMcLeod** [comment]
You are correct. Thank you for pointing this out to me. The library has been fixed. 

I hope the simple library can be useful for you. Let me know if you have any additional features you would like, and I could try to add them.
